In [1]:
import numpy as np

# 1.create a null vector of size 10

In [2]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 2.create a vector with values ranging from 10 to 49

In [3]:
vector = np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 3.Find the shape of previous array in question 3

In [4]:
vector.shape

(39,)

# 4.Print the type of the previous array in question 3

In [5]:
vector.dtype

dtype('int32')

# 5.Print the numpy version and the configuration


In [6]:
import numpy
print(np.__version__)
numpy.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

# 6.Print the dimension of the array in question 3

In [7]:
vector.ndim

1

# 7.Create a boolean array with all the True values

In [8]:
vector>9

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

# 8.Create a two dimensional array

In [11]:
dim2_array = np.array(range(24))
dim2_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
dim2_array.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

# 9.Create a three dimensional array

In [13]:
dim3_array = np.array(range(24))
dim3_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
dim3_array.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Difficulty Level Easy
10.Reverse a vector (first element becomes last)

In [15]:
reverse_vector = [1,2,3,4,5,6,7,8,9,10]
reverse_vector = reverse_vector[::-1]
reverse_vector

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# 11.Create a null vector of size 10 but the fifth value which is 1

In [16]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
null_vector[4] = 1

In [19]:
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 12.Create a 3x3 identity matrix

In [20]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 13.arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float



In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)
arr.dtype

dtype('float64')

# 14.arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
Multiply arr1 with arr2

In [23]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
a=np.multiply(arr1,arr2)
a

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

# 15.arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [24]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2[arr2>arr1]

array([ 4.,  7., 12.])

# 16.Extract all odd numbers from arr with values(0-9)

In [25]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]

array([1, 3, 5, 7, 9])

# 17.Replace all odd numbers to -1 from previous array

In [26]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1] = 0
arr[3] = 0
arr[4] = 0
arr[7] = 0
arr[9] = 0
arr

array([0, 0, 2, 0, 0, 5, 6, 0, 8, 0])

# 18.arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [27]:
arr = np.arange(10)
arr[5] = 12
arr[6] = 12
arr[7] = 12
arr[8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

# 19.Create a 2d array with 1 on the border and 0 inside

In [28]:
arr2d = np.array ([[1,0,0,0,1], [1,0,0,0,1]])
arr2d

array([[1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

# 20. Difficulty Level Medium

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Replace the value 5 to 12

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1] =12
arr2d[1,1]

12

In [30]:
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

# 21.
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [31]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[1,1] = 64
arr3d[1,1]

array([64, 64, 64])

# 22.Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it


In [32]:
arr = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr[0, 0:]

array([0, 1, 2, 3, 4])

# 23.Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it


In [33]:
arr = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr[1,1:2]

array([6])

# 24.Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
arr = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr[]

# 25.Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.08562208 0.06358148 0.61447532 0.33609021 0.04573609 0.05056987
  0.33530758 0.23306325 0.75256197 0.09547961]
 [0.47436938 0.41218922 0.31007683 0.13259444 0.94655687 0.40053073
  0.77341707 0.45104657 0.57258594 0.28786892]
 [0.54356543 0.24484393 0.48216039 0.60695744 0.19391858 0.13340802
  0.33900398 0.01903713 0.49004735 0.70268908]
 [0.21040879 0.2339531  0.59665929 0.17463193 0.49016105 0.40997373
  0.22446724 0.54961822 0.02141117 0.25475446]
 [0.43933701 0.94175424 0.79428685 0.20806548 0.12821593 0.38394839
  0.89767977 0.97344016 0.40403111 0.30798288]
 [0.93244341 0.43170417 0.31100478 0.1510641  0.01598378 0.59828756
  0.01706142 0.69963817 0.08310252 0.24060397]
 [0.16754652 0.06494933 0.17099093 0.96752371 0.90282833 0.90593552
  0.1381129  0.4637158  0.28184726 0.72063273]
 [0.95862115 0.49755565 0.63507141 0.47212249 0.19953525 0.15304085
  0.48167042 0.81694996 0.0224983  0.07299927]
 [0.4345497  0.6228789  0.47776518 0.96320722 0.79305631 0.05954

# 26. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])¶
Find the common items between a and b

In [35]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

# 27.a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# 28.names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# 29.names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Jo

In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

# 30.Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15

In [49]:
arr2d = np.array ([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# 31.Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16

In [50]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr4 = arr3.reshape(2,2,4)
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

# 32.Swap axes of the array you created in Question 32

In [51]:
arr4.swapaxes(1,2).shape

(2, 4, 2)

# 33. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 033.

In [53]:
arr = np.array([0.1,16,9,25,81,64, 121, 169, 400, 2500])
a= np.sqrt(arr)
print(a)
a[a < .5] = 0
print(a)

[ 0.31622777  4.          3.          5.          9.          8.
 11.         13.         20.         50.        ]
[ 0.  4.  3.  5.  9.  8. 11. 13. 20. 50.]


# 34.Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [54]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

# 35.names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
[names[i] for i in sorted(np.unique(names, return_index=True)[1])]

['Bob', 'Joe', 'Will']

# 36.a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [56]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
result

array([1, 2, 3, 4])

# 37.Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [57]:
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])


np.delete(sampleArray, 1,0 )

array([[34, 43, 73],
       [53, 94, 66]])

# 38.x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matri

In [58]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

# 39.Generate a matrix of 20 random values and find its cumulative sum

In [59]:
x = np.random.random((20))
a= np.cumsum(x)
a

array([0.18547165, 0.78976372, 0.9188045 , 1.84924513, 1.93127551,
       2.27609694, 3.23347549, 3.54054733, 3.83024783, 4.15726132,
       4.29897477, 4.99156148, 5.12378584, 5.56426565, 5.92535687,
       6.6389475 , 7.25082903, 7.29253104, 7.49474505, 7.66355952])

# 40.Stack arrays a and b vertically

In [60]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 41. Stack the arrays a and b horizontally.

In [62]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 42.Create the following pattern without hardcoding. #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [63]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 43. Reverse the rows of a 2D array arr.

In [64]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 44.Reverse the columns of a 2D array arr.

In [65]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 45.Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [66]:
np.set_printoptions(threshold=3)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# 46.Swap rows 1 and 2 in the array arr.

In [67]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 47. .Object containing evenly spaced values within a defined interval

In [68]:
b = np.arange(5,22,2)
b

array([ 5,  7,  9, ..., 17, 19, 21])

# 48.Compute the arithmetic mean along the specified axis

In [69]:
a = np.array([[1, 2], [3, 4]])
print(a)
np.mean(a)

[[1 2]
 [3 4]]


2.5

# 49.Counts the number of non-zero values in the array a

In [70]:
a = np.array([[0, 1, 7, 0],
              [3, 0, 2, 19]])
np.count_nonzero(a)

5

# 50.Reverse or permute the axes of an array; returns the modified array.

In [71]:
x = np.arange(4).reshape((2,2))
print(x)
np.transpose(x)

[[0 1]
 [2 3]]


array([[0, 2],
       [1, 3]])